"""Toy long-only, binary-contract execution and finite-cash accounting.

Orders are hand-specified attempts, not generated by a signal. Valid books have
cent-denominated prices in [0, 1], positive asks, integer displayed quantities and
nonnegative integer clocks. Both book and receipt times are checked. Receipt must
be strictly before the decision; age is measured from the book timestamp, with
the configured maximum included. A book timestamp after its receipt is invalid.

Execution is all-or-none at the displayed ask. Consumed ask depth is tracked per
quote ID; a fresh quote is assumed to be a fresh snapshot, not incremental depth.
Fees are a disclosed toy proportional schedule, rounded UP to cents per fill.
Principal is locked, fees paid immediately, and cash cannot become negative.
There are no sales, shorts, borrowing, partial fills, queue models, or slippage.

Only verified terminal settlements available strictly before the current cutoff
release principal and credit the declared binary payout. A record's effective
time alone is never sufficient. Cutoffs and decisions cannot go backwards; same
cutoff processing is allowed but cannot expose same-tick external information.
Settlements are immutable and idempotent across calls. Conflicting terminal
outcomes are rejected; corrections/reversals and real settlement verification
are deliberately outside this demonstration.
"""

from dataclasses import dataclass
from decimal import Decimal, ROUND_CEILING

from .temporal import require_decimal, require_id, require_tick, unique_ids

CENT = Decimal("0.01")
ZERO = Decimal("0.00")
ONE = Decimal("1")


def money(value: Decimal) -> str:
    return format(value, ".2f")


@dataclass(frozen=True)
class Quote:
    """Raw quote fields are validated on use, allowing bad-feed rejection tests."""

    quote_id: str
    token: str
    book_at: int
    received_at: int
    bid: Decimal
    ask: Decimal
    bid_depth: int
    ask_depth: int


@dataclass(frozen=True)
class OrderAttempt:
    order_id: str
    parent_event_id: str
    token: str
    decision_at: int
    quantity: int

    def __post_init__(self):
        for name in ("order_id", "parent_event_id", "token"):
            require_id(getattr(self, name), name)
        require_tick(self.decision_at, "decision_at")
        if type(self.quantity) is not int or self.quantity <= 0:
            raise ValueError("quantity must be a positive integer")


def quote_reasons(quote: Quote, order: OrderAttempt, max_quote_age: int):
    """Return ordered rejection reasons; do not repair malformed feed values."""
    require_tick(max_quote_age, "max_quote_age")
    reasons = []
    if quote.token != order.token:
        reasons.append("token_mismatch")
    try:
        require_id(quote.quote_id, "quote_id")
        require_id(quote.token, "token")
        require_tick(quote.book_at, "book_at")
        require_tick(quote.received_at, "received_at")
        for field in ("bid", "ask"):
            price = getattr(quote, field)
            require_decimal(price, field, minimum=ZERO)
            if price > ONE or price.quantize(CENT) != price:
                raise ValueError("prices must be cent-denominated and at most one")
        if quote.ask <= ZERO:
            raise ValueError("ask must be positive")
        for field in ("bid_depth", "ask_depth"):
            if type(getattr(quote, field)) is not int or getattr(quote, field) < 0:
                raise ValueError("depth must be a nonnegative integer")
    except (ValueError, ArithmeticError):
        reasons.append("bad_quote_values")
        return reasons
    if quote.book_at > order.decision_at:
        reasons.append("future_quote")
    if quote.received_at >= order.decision_at:
        reasons.append("quote_not_yet_received")
    if quote.book_at > quote.received_at:
        reasons.append("inconsistent_quote_times")
    if order.decision_at - quote.book_at > max_quote_age:
        reasons.append("stale_quote")
    if quote.bid > quote.ask:
        reasons.append("crossed_book")
    return reasons


@dataclass(frozen=True)
class Settlement:
    settlement_id: str
    parent_event_id: str
    token: str
    effective_at: int
    available_at: int
    verified: bool
    verified_at: int | None
    payout_per_unit: Decimal

    def __post_init__(self):
        for name in ("settlement_id", "parent_event_id", "token"):
            require_id(getattr(self, name), name)
        require_tick(self.effective_at, "effective_at")
        require_tick(self.available_at, "available_at")
        if type(self.verified) is not bool:
            raise ValueError("verified must be a boolean")
        if self.available_at < self.effective_at:
            raise ValueError("settlement cannot be available before it is effective")
        if self.verified:
            require_tick(self.verified_at, "verified_at")
            if not self.effective_at <= self.verified_at <= self.available_at:
                raise ValueError("require effective_at <= verified_at <= available_at")
        elif self.verified_at is not None:
            raise ValueError("unverified settlement must have verified_at=None")
        require_decimal(self.payout_per_unit, "payout_per_unit")
        if self.payout_per_unit not in (ZERO, ONE):
            raise ValueError("toy binary payout must be zero or one")


@dataclass(frozen=True)
class Position:
    order_id: str
    parent_event_id: str
    token: str
    quantity: int
    principal: Decimal


class Ledger:
    """In-memory single-account ledger; malformed batch requests fail before mutation."""

    def __init__(self, initial_cash: Decimal, fee_bps: Decimal, max_quote_age: int):
        require_decimal(initial_cash, "initial_cash", minimum=ZERO)
        require_decimal(fee_bps, "fee_bps", minimum=ZERO)
        require_tick(max_quote_age, "max_quote_age")
        if initial_cash.quantize(CENT) != initial_cash:
            raise ValueError("initial cash must be cent-denominated")
        if fee_bps > Decimal("10000"):
            raise ValueError("fee_bps cannot exceed 10000 in this toy schedule")
        self.available_cash = initial_cash
        self.fees_paid = ZERO
        self.fee_bps = fee_bps
        self.max_quote_age = max_quote_age
        self.at = -1
        self._orders = set()
        self._quotes = {}
        self._used_depth = {}
        self._positions = {}
        self._settlement_records = {}
        self._terminal = {}
        self._token_events = {}

    def snapshot(self):
        return {
            "at": self.at,
            "available_cash": money(self.available_cash),
            "locked_principal": money(sum((p.principal for p in self._positions.values()), ZERO)),
            "fees_paid": money(self.fees_paid),
            "open_order_ids": sorted(self._positions),
            "known_settled_tokens": sorted(self._terminal),
        }

    def _check_clock(self, at):
        require_tick(at, "cutoff")
        if at < self.at:
            raise ValueError("ledger clock cannot move backwards")

    def attempt(self, order: OrderAttempt, quote: Quote):
        self._check_clock(order.decision_at)
        if order.order_id in self._orders:
            raise ValueError(f"duplicate order_id: {order.order_id}")
        existing_event = self._token_events.get(order.token)
        if existing_event is not None and existing_event != order.parent_event_id:
            raise ValueError("token has conflicting parent event identity")
        reasons = quote_reasons(quote, order, self.max_quote_age)
        if not reasons and quote.quote_id in self._quotes and self._quotes[quote.quote_id] != quote:
            raise ValueError("quote_id reused with different contents")
        if order.token in self._terminal:
            reasons.append("contract_already_settled")
        principal, fee = ZERO, ZERO
        if not reasons:
            remaining_depth = quote.ask_depth - self._used_depth.get(quote.quote_id, 0)
            if order.quantity > remaining_depth:
                reasons.append("insufficient_displayed_depth")
            principal = order.quantity * quote.ask
            fee = (principal * self.fee_bps / Decimal("10000")).quantize(CENT, rounding=ROUND_CEILING)
            if principal + fee > self.available_cash:
                reasons.append("insufficient_available_cash")
        self.at = order.decision_at
        self._orders.add(order.order_id)
        if not quote_reasons(quote, order, self.max_quote_age):
            self._quotes[quote.quote_id] = quote
        accepted = not reasons
        if accepted:
            self.available_cash -= principal + fee
            self.fees_paid += fee
            self._positions[order.order_id] = Position(
                order.order_id, order.parent_event_id, order.token, order.quantity, principal
            )
            self._used_depth[quote.quote_id] = self._used_depth.get(quote.quote_id, 0) + order.quantity
            self._token_events[order.token] = order.parent_event_id
        return {
            "order_id": order.order_id, "accepted": accepted, "reasons": reasons,
            "principal_locked": money(principal) if accepted else "0.00",
            "fee_paid": money(fee) if accepted else "0.00",
            "state": self.snapshot(),
        }

    def apply_settlements(self, records, as_of: int):
        self._check_clock(as_of)
        records = list(records)
        unique_ids(records, "settlement_id")
        # Build candidate state first: one bad/conflicting record cannot partially settle a batch.
        terminal = dict(self._terminal)
        known_records = dict(self._settlement_records)
        token_events = dict(self._token_events)
        statuses = {}
        for record in sorted(records, key=lambda item: item.settlement_id):
            if record.available_at >= as_of:
                statuses[record.settlement_id] = "not_yet_available"
                continue
            previous = known_records.get(record.settlement_id)
            if previous is not None and previous != record:
                raise ValueError("settlement_id reused with different contents")
            known_records[record.settlement_id] = record
            if not record.verified:
                statuses[record.settlement_id] = "unverified"
                continue
            event = token_events.get(record.token)
            if event is not None and event != record.parent_event_id:
                raise ValueError("settlement has conflicting parent event identity")
            previous_terminal = terminal.get(record.token)
            if previous_terminal is not None and previous_terminal.payout_per_unit != record.payout_per_unit:
                raise ValueError("conflicting verified terminal settlements")
            token_events[record.token] = record.parent_event_id
            terminal[record.token] = record
            statuses[record.settlement_id] = "verified_and_available"
        released, credit, settled_order_ids = ZERO, ZERO, []
        positions = dict(self._positions)
        for order_id, position in sorted(self._positions.items()):
            record = terminal.get(position.token)
            if record is not None:
                released += position.principal
                credit += position.quantity * record.payout_per_unit
                settled_order_ids.append(order_id)
                del positions[order_id]
        self.at = as_of
        self.available_cash += credit
        self._positions, self._terminal = positions, terminal
        self._settlement_records, self._token_events = known_records, token_events
        return {
            "as_of": as_of, "record_statuses": statuses,
            "settled_order_ids": settled_order_ids,
            "principal_released": money(released), "cash_credited": money(credit),
            "state": self.snapshot(),
        }
